exclude_checks = [
    "com.google.fonts/check/interpolation_issues",
    "com.google.fonts/check/outline_direction",
    "com.google.fonts/check/outline_colinear_vectors",
    "com.google.fonts/check/outline_jaggy_segments",
    "com.google.fonts/check/outline_semi_vertical"
]
